In [1]:
import numpy as np

- create
- basic operation
- math operation
- indexing and slicing
- boolean filter

In [6]:
x =np.array([1,2,3,4,5])
print(x)
print(x.shape)

[1 2 3 4 5]
(5,)


In [8]:
a = np.array([[1,2,3],[4,5,6]])
print(a)
print(a.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)


In [9]:
b = np.array([[1,2,3],[4,5,6],[7,9,9]])
print(b)
print(b.shape)

[[1 2 3]
 [4 5 6]
 [7 9 9]]
(3, 3)


In [10]:
z = [0,1,2,3,4,5,6,7,8,9]
nz = np.array([z]*10)
print(nz)
print(nz.shape)

[[0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]]
(10, 10)


- random
- arange
- linspace


In [11]:
np.random.rand(3,3)

array([[0.44235973, 0.43439845, 0.45390851],
       [0.23404744, 0.78402967, 0.57445498],
       [0.63621963, 0.05679966, 0.21733466]])

In [15]:
r1 =np.random.randint(-5,6,size=(5,5))
print(r1)

[[ 5  0 -5  1  2]
 [-2  1 -5  2  5]
 [ 0  2 -2  5  5]
 [-1 -4  3  4 -2]
 [-2  5 -2  4 -5]]


In [18]:
#start,stop,gap
np.arange(0,100, .6)

array([ 0. ,  0.6,  1.2,  1.8,  2.4,  3. ,  3.6,  4.2,  4.8,  5.4,  6. ,
        6.6,  7.2,  7.8,  8.4,  9. ,  9.6, 10.2, 10.8, 11.4, 12. , 12.6,
       13.2, 13.8, 14.4, 15. , 15.6, 16.2, 16.8, 17.4, 18. , 18.6, 19.2,
       19.8, 20.4, 21. , 21.6, 22.2, 22.8, 23.4, 24. , 24.6, 25.2, 25.8,
       26.4, 27. , 27.6, 28.2, 28.8, 29.4, 30. , 30.6, 31.2, 31.8, 32.4,
       33. , 33.6, 34.2, 34.8, 35.4, 36. , 36.6, 37.2, 37.8, 38.4, 39. ,
       39.6, 40.2, 40.8, 41.4, 42. , 42.6, 43.2, 43.8, 44.4, 45. , 45.6,
       46.2, 46.8, 47.4, 48. , 48.6, 49.2, 49.8, 50.4, 51. , 51.6, 52.2,
       52.8, 53.4, 54. , 54.6, 55.2, 55.8, 56.4, 57. , 57.6, 58.2, 58.8,
       59.4, 60. , 60.6, 61.2, 61.8, 62.4, 63. , 63.6, 64.2, 64.8, 65.4,
       66. , 66.6, 67.2, 67.8, 68.4, 69. , 69.6, 70.2, 70.8, 71.4, 72. ,
       72.6, 73.2, 73.8, 74.4, 75. , 75.6, 76.2, 76.8, 77.4, 78. , 78.6,
       79.2, 79.8, 80.4, 81. , 81.6, 82.2, 82.8, 83.4, 84. , 84.6, 85.2,
       85.8, 86.4, 87. , 87.6, 88.2, 88.8, 89.4, 90

In [19]:
# start, stop, number_of_item
np.linspace(0,50,100)

array([ 0.        ,  0.50505051,  1.01010101,  1.51515152,  2.02020202,
        2.52525253,  3.03030303,  3.53535354,  4.04040404,  4.54545455,
        5.05050505,  5.55555556,  6.06060606,  6.56565657,  7.07070707,
        7.57575758,  8.08080808,  8.58585859,  9.09090909,  9.5959596 ,
       10.1010101 , 10.60606061, 11.11111111, 11.61616162, 12.12121212,
       12.62626263, 13.13131313, 13.63636364, 14.14141414, 14.64646465,
       15.15151515, 15.65656566, 16.16161616, 16.66666667, 17.17171717,
       17.67676768, 18.18181818, 18.68686869, 19.19191919, 19.6969697 ,
       20.2020202 , 20.70707071, 21.21212121, 21.71717172, 22.22222222,
       22.72727273, 23.23232323, 23.73737374, 24.24242424, 24.74747475,
       25.25252525, 25.75757576, 26.26262626, 26.76767677, 27.27272727,
       27.77777778, 28.28282828, 28.78787879, 29.29292929, 29.7979798 ,
       30.3030303 , 30.80808081, 31.31313131, 31.81818182, 32.32323232,
       32.82828283, 33.33333333, 33.83838384, 34.34343434, 34.84

- shape
- dtype
- ndim
- size

basic operations
- sum
- mean
- min
- max
- std
- reshape
- transpose
- flatten

In [20]:
x.dtype

dtype('int64')

In [21]:
x = np.random.rand(3,3)
x.dtype

dtype('float64')

In [22]:
x.ndim

2

In [25]:
z = np.random.randint(1,5,(3,3,3))
z.ndim

3

In [26]:
z.size

27

In [27]:
z.sum()

np.int64(78)

In [33]:
a = np.random.rand(2,3)
print(a.sum())
print(a.sum(axis=0))#column-size
print(a.sum(axis=1))# row-wise

print(a.mean())
print(a.max())
print(a.std())
print(a.var())
#all hte methods can be used with axis




3.594280389549292
[1.09201805 1.76656111 0.73570122]
[2.11911594 1.47516445]
0.5990467315915486
0.9560266872251528
0.24454097558292517
0.0598002887390488


In [36]:
z = np.random.randint(11,99, (5,5))
print(z)
print('transpose')
print(z.transpose())# or print(z.T)
print('flattened')
print(z.flatten)

[[72 64 64 56 70]
 [47 22 88 59 97]
 [14 62 42 31 41]
 [20 28 86 35 58]
 [22 33 33 21 17]]
transpose
[[72 47 14 20 22]
 [64 22 62 28 33]
 [64 88 42 86 33]
 [56 59 31 35 21]
 [70 97 41 58 17]]
flattened
<built-in method flatten of numpy.ndarray object at 0x000002316D045530>


In [38]:
a = np.random.randint(1,10, (4,5))
print(a)
print(a.reshape(20))
print(a.reshape(5,4))
print(a.reshape(2,10))
print(a.reshape(5,2,2))


[[1 7 3 1 8]
 [4 8 3 9 6]
 [8 3 5 8 7]
 [5 9 7 6 2]]
[1 7 3 1 8 4 8 3 9 6 8 3 5 8 7 5 9 7 6 2]
[[1 7 3 1]
 [8 4 8 3]
 [9 6 8 3]
 [5 8 7 5]
 [9 7 6 2]]
[[1 7 3 1 8 4 8 3 9 6]
 [8 3 5 8 7 5 9 7 6 2]]
[[[1 7]
  [3 1]]

 [[8 4]
  [8 3]]

 [[9 6]
  [8 3]]

 [[5 8]
  [7 5]]

 [[9 7]
  [6 2]]]


In [39]:
a = np.array([[1,2],[3,4]])
b = np.array([[6,2],[6,3]])
print(a)
print(b)

[[1 2]
 [3 4]]
[[6 2]
 [6 3]]


In [42]:
print(a + b)
print(a - b)
print(a/b) #element-wise division
print(a*b)#element-wise multipilcation
print(a@b)# matrix multiplication
print(a.dot(b))# matrix multiplication

[[7 4]
 [9 7]]
[[-5  0]
 [-3  1]]
[[0.16666667 1.        ]
 [0.5        1.33333333]]
[[ 6  4]
 [18 12]]
[[18  8]
 [42 18]]
[[18  8]
 [42 18]]


In [43]:
# when using matrix and scalar
print(a - 10)# broadcasting
print(a*10)# broadcasting
print(a/b)# broadcasting
print(a +10)

[[-9 -8]
 [-7 -6]]
[[10 20]
 [30 40]]
[[0.16666667 1.        ]
 [0.5        1.33333333]]
[[11 12]
 [13 14]]


In [45]:
# indexing
a[0,0]

np.int64(1)

In [54]:
#slicing
b = np.random.randint(1, 10,(5,5))
print(b)
print(b[:,0])#first column
print(b[:,-1])#second column
print(b[:,:3])#third column
print(b[1:-1,1:-1])

[[5 1 7 7 1]
 [9 7 9 8 9]
 [6 7 8 2 9]
 [4 6 4 1 5]
 [8 9 7 8 2]]
[5 9 6 4 8]
[1 9 9 5 2]
[[5 1 7]
 [9 7 9]
 [6 7 8]
 [4 6 4]
 [8 9 7]]
[[7 9 8]
 [7 8 2]
 [6 4 1]]
